# Generated by Django 5.0.6 on 2024-07-28 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('dni', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('nombre_mascota', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mascota', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('sexo', models.CharField(max_length=6)),
                ('especie', models.CharField(max_length=10)),
                ('raza', models.CharField(max_length=50)),
                ('propietario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petservice.propietario')),
                ('profesional_a_cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petservice.veterinario')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desparasitacion', models.DateField(blank=True, null=True)),
                ('vacunacion', models.DateField(blank=True, null=True)),
                ('chequeo_sangre', models.DateField(blank=True, null=True)),
                ('servicio_peluqueria', models.DateField(blank=True, null=True)),
                ('alimento', models.CharField(blank=True, max_length=100, null=True)),
                ('varios', models.CharField(blank=True, default='', max_length=150)),
                ('mascota', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petservice.mascota')),
            ],
        ),
    ]
