# Generated by Django 5.0.6 on 2024-07-30 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petservice', '0002_alter_mascota_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='edad',
        ),
    ]
