# Generated by Django 5.0.6 on 2024-07-30 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petservice', '0003_remove_mascota_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
